### PR TITLE
Merge 3.0.0 code

### PR DESCRIPTION
**Pull request by jamesclark92**
See <https://github.com/jamesclark92/angular-zxcvbn> fork for full information. 

Please give me your feedback and if there are any changes you want me to make before you merge the code

I doubt it will pass your tests, however I have updated the .travis.yml file so once that has been merged the tests should pass.

If you want to build it and run the tests, enter these 3 commands in the command line:
```bash
npm install
bower install
gulp
```

### CODE REVIEW

**Comment by ghostbar** [comment]
That was excellent; thank you James!

**Comment by jamesclark92** [comment]
Do you want to make a 3.0.0 release as well? (preferably without the "v" at the front).
I had used git to tag it in my commit (git tag 3.0.0, git push --tags) but for some reason that wasn't merged across.

Date: Wed, 30 Dec 2015 21:36:22 -0800

**Comment by ghostbar** [comment]
Done

**Comment by jamesclark92** [comment]
Brilliant! Although I have immediately found an error ;) My bad!!!

Date: Thu, 31 Dec 2015 08:21:25 -0800

**Pull request merged**
